//	Ayomide Alaka
/*
	This program calculates the revenue from seat sales.
	There are three categories of seats available, A,B,C.
*/

#include <iostream>
#include <iomanip>

using namespace std;

int main() {
	double
		priceA = 15.0,
		priceB = 12.0,
		priceC = 9.0,
		revenueA,
		revenueB,
		revenueC,
		grandTotal;
	int
		quantityA,
		quantityB,
		quantityC;
	char
		again;


	//	Display Program Title
	cout << "Stadium Seats Calculator" << endl;
	cout << "-----------------------------\n" << endl;

	//	Collect input from user.
	cout << "How many seats 'A' were sold?" << endl;
	cin >> quantityA;

	while (quantityA < 0) {
		cout << "You cannot have a negative count on the seats\n";
		cout << "Enter a new value for seats sold: ";
		cin >> quantityA;
	}

	cout << "How many seats 'B' were sold?" << endl;
	cin >> quantityB;

	while (quantityB < 0) {
		cout << "You cannot have a negative count on the seats\n";
		cout << "Enter a new value for seats sold: ";
		cin >> quantityB;
	}

	cout << "How many seats 'C' were sold?" << endl;
	cin >> quantityC;

	while (quantityC < 0) {
		cout << "You cannot have a negative count on the seats\n";
		cout << "Enter a new value for seats sold: ";
		cin >> quantityC;
	}

	//	Calculate the revenue from each seat.
	revenueA = quantityA * priceA;
	revenueB = quantityB * priceB;
	revenueC = quantityC * priceC;

	//	Calculate grand total.
	grandTotal = revenueA + revenueB + revenueC;

	// Display Results
	cout << fixed << showpoint << setprecision(2); //	fixes the decimal to 2 decimal places
	cout << "-------------------------------------------\n" << endl;
	cout << "The amount generated by Seats 'A' is: " << revenueA << "\n" << endl;
	cout << "The amount generated by Seats 'B' is: " << revenueB << "\n" << endl;
	cout << "The amount generated by Seats 'C' is: " << revenueC << "\n" << endl;
	cout << "-------------------------------------------" << endl;
	cout << "Grand Total is: " << grandTotal << endl;

	cout << "Would you like to do it again? \n(Enter 'Y' for yes or 'N' for no.)" << endl;
	cin >> again;

	while (!(again == 'Y' || again == 'y' || again == 'N' || again == 'n'))
	{
		cout << "You entered an invalid option \nPlease enter the characters 'y' or 'n'" << endl;
		cin >> again;
	}


	return 0;
}
